### ISSUE TITLE
diff large PE files issue

### ISSUE THREAD

**Issue by flyninja** [ohjeongwook/DarunGrim#14]
like as mshtml ms14-65 vs. ms14-80, log output:

```
[02/17/2015 10:24:11]  [DarunGrim] DiffMachine::_Load
[02/17/2015 10:24:11]  [DarunGrim] SourceFunctionAddress: 0
[02/17/2015 10:24:11]  [DarunGrim] Analyze
[02/17/2015 10:24:11]  [DarunGrim] DiffMachine::Analyze: Fingerprint Map Size 0:0
[02/17/2015 10:24:11]  [DarunGrim] Name Match
[02/17/2015 10:24:11]  [DarunGrim] Name Match Ended
[02/17/2015 10:24:11]  [DarunGrim] DiffMachine::Analyze: Name matched number=0
[02/17/2015 10:24:11]  [DarunGrim] DiffMachine::Analyze: DoFingerPrintMatch
[02/17/2015 10:24:11]  [DarunGrim] DiffMachine::DoFingerPrintMatch: Matched pair count=0
[02/17/2015 10:24:11]  [DarunGrim] DiffMachine::Analyze: Match Map Size: 0
[02/17/2015 10:24:11]  [DarunGrim] DiffMachine::Analyze: DoIsomorphMatch
[02/17/2015 10:24:11]  [DarunGrim] DiffMachine::Analyze: Match Map Size: 0
[02/17/2015 10:24:11]  [DarunGrim] DiffMachine::GenerateFunctionMatchInfo: FunctionMatchList.size()=0
[02/17/2015 10:24:11]  [DarunGrim] DiffMachine::GenerateFunctionMatchInfo: unpatched_unidentified_number=0
[02/17/2015 10:24:11]  [DarunGrim] DiffMachine::GenerateFunctionMatchInfo: patched_unidentified_number=0
[02/17/2015 10:24:11]  [DarunGrim] DiffMachine::GenerateFunctionMatchInfo: FunctionMatchList.size()=0
[02/17/2015 10:24:11]  [DarunGrim] DiffMachine::GenerateFunctionMatchInfo: unpatched_unidentified_number=0
[02/17/2015 10:24:11]  [DarunGrim] DiffMachine::GenerateFunctionMatchInfo: patched_unidentified_number=0
[02/17/2015 10:24:11]  [DarunGrim] Save
[02/17/2015 10:24:11]  [DarunGrim] DiffResults->MatchMap.size()=0
[02/17/2015 10:24:11]  [DarunGrim] DiffResults->MatchMap.size()=0
[02/17/2015 10:24:11]  [DarunGrim] FunctionMatchList.size()=0
```

**Comment by kimchicon** [comment]
Can you describe the environment you have?

1. IDA version and installation path 
2. The files (mshtml) you used for diffing?

Probably you can try this too: https://mattoh.wordpress.com/2014/05/05/big-file-diffing-with-darungrim/

**Comment by flyninja** [comment]
Thank for replay.
1. Win-7-x64, IDA 6.1, C:\Programm Files(86)\ida61, DG run with admin-priv.
2. mshtml.dll https://www.microsoft.com/en-us/download/details.aspx?id=45134  vs. https://www.microsoft.com/en-us/download/details.aspx?id=44621

I think but it's truble not depend on large-size. On small-size files DG give me analogue result. Bug in my bug-report - not full log. More important part is:
```
Perform Diffing...
Diffing process finished.Traceback (most recent call last):
  File "<string>", line 896, in newFromFileStore
  File "<string>", line 1032, in StartPerformDiff
  File "<string>", line 1331, in OpenDatabase
  File "<string>", line 1070, in synchronizeIDA
  File "C:\mat\Src\DarunGrim\Src\Scripts\build\DarunGrim\out00-PYZ.pyz\DarunGrimDatabase", line 782, in GetFilesLocation
  File "C:\mat\Src\DarunGrim\Src\Scripts\build\DarunGrim\out00-PYZ.pyz\sqlalchemy.orm.query", line 2320, in all
  File "C:\mat\Src\DarunGrim\Src\Scripts\build\DarunGrim\out00-PYZ.pyz\sqlalchemy.orm.query", line 2438, in __iter__
  File "C:\mat\Src\DarunGrim\Src\Scripts\build\DarunGrim\out00-PYZ.pyz\sqlalchemy.orm.query", line 2453, in _execute_and_instances
  File "C:\mat\Src\DarunGrim\Src\Scripts\build\DarunGrim\out00-PYZ.pyz\sqlalchemy.engine.base", line 729, in execute
  File "C:\mat\Src\DarunGrim\Src\Scripts\build\DarunGrim\out00-PYZ.pyz\sqlalchemy.sql.elements", line 322, in _execute_on_connection
  File "C:\mat\Src\DarunGrim\Src\Scripts\build\DarunGrim\out00-PYZ.pyz\sqlalchemy.engine.base", line 826, in _execute_clauseelement
  File "C:\mat\Src\DarunGrim\Src\Scripts\build\DarunGrim\out00-PYZ.pyz\sqlalchemy.engine.base", line 958, in _execute_context
  File "C:\mat\Src\DarunGrim\Src\Scripts\build\DarunGrim\out00-PYZ.pyz\sqlalchemy.engine.base", line 1159, in _handle_dbapi_exception
  File "C:\mat\Src\DarunGrim\Src\Scripts\build\DarunGrim\out00-PYZ.pyz\sqlalchemy.util.compat", line 199, in raise_from_cause
  File "C:\mat\Src\DarunGrim\Src\Scripts\build\DarunGrim\out00-PYZ.pyz\sqlalchemy.engine.base", line 951, in _execute_context
  File "C:\mat\Src\DarunGrim\Src\Scripts\build\DarunGrim\out00-PYZ.pyz\sqlalchemy.engine.default", line 436, in do_execute
sqlalchemy.exc.OperationalError: (OperationalError) no such table: Source.FileInfo u'SELECT "Source"."FileInfo"."OriginalFilePath" AS "Source_FileInfo_OriginalFilePath", "Source"."FileInfo"."ComputerName" AS "Source_FileInfo_ComputerName", "Source"."FileInfo"."UserName" AS "Source_FileInfo_UserName", "Source"."FileInfo"."CompanyName" AS "Source_FileInfo_CompanyName", "Source"."FileInfo"."FileVersion" AS "Source_FileInfo_FileVersion", "Source"."FileInfo"."FileDescription" AS "Source_FileInfo_FileDescription", "Source"."FileInfo"."InternalName" AS "Source_FileInfo_InternalName", "Source"."FileInfo"."ProductName" AS "Source_FileInfo_ProductName", "Source"."FileInfo"."ModifiedTime" AS "Source_FileInfo_ModifiedTime", "Source"."FileInfo"."MD5Sum" AS "Source_FileInfo_MD5Sum", "Source"."FileInfo".id AS "Source_FileInfo_id" \nFROM "Source"."FileInfo"' ()
```
Exception throws in GetFilesLocation when ```self.SessionInstance.query(SourceFileInfo).all()``` invokes. My sql-engine is bad?
I have installed python 2.7.9 by default, may be DG need same extentions-libs as dependensies? Where I may read doc about this?

**Comment by ohjeongwook** [comment]
Can you pass me the .db file that makes the exception? I guess the database is somehow corrupt.

**Comment by flyninja** [comment]
Shure. [It's link on sendspace](https://www.sendspace.com/file/f9hxqt) to download both .idb. I so try use IDA 6.5, with same fault.

**Comment by flyninja** [comment]
Sorry for timeout, technical problems. [This link on sendspace](https://www.sendspace.com/file/yv3ud1) to download .dgf file comparation .idb-th.

**Comment by vgturtle127** [comment]
Closing due to inactivity.
